apiVersion: app.shn.me/v1
kind: BookStore
metadata:
  labels:
    app.kubernetes.io/name: bookstore-controller-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: bookstore-sample
spec:
  deploymentName: bookstore
  replicas: 3
  containerPort: 3000
  deploymentImageName: shn27/book-store
  deploymentImageTag: "4.0"